# Generated by Django 3.0.2 on 2020-02-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200229_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Dog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Article'),
        ),
    ]
