# Generated by Django 3.0.2 on 2020-02-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200229_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='product',
            new_name='article',
        ),
    ]
