# Generated by Django 3.0.2 on 2020-02-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200229_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article',
            new_name='product',
        ),
    ]
