# Generated by Django 3.0.2 on 2020-02-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200229_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='type',
            field=models.CharField(choices=[('C', 'Carousel'), ('P', 'Primary'), ('S', 'Secondary'), ('B', 'Bottom')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('D', 'Dog'), ('P', 'Product')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('D', 'Dog'), ('P', 'Product')], max_length=1),
        ),
    ]
