# Generated by Django 3.0.2 on 2020-03-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200229_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='featured',
            name='type',
            field=models.CharField(choices=[('C', 'Carousel')], max_length=1),
        ),
    ]
