# Generated by Django 3.0.2 on 2020-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200305_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('C', 'Comestibles'), ('S', 'Atuendos'), ('A', 'Accesorios'), ('O', 'Otros')], default='O', max_length=1),
        ),
    ]
