# Generated by Django 3.0.5 on 2020-04-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado')], max_length=45),
        ),
    ]
