# Generated by Django 3.0.5 on 2020-04-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20200402_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Activa'), ('F', 'Finalizada')], max_length=1, null=True),
        ),
    ]
